swagger: "2.0"
info:
  description: beego Test API
  version: 1.0.0
paths:
  /:
    get:
      tags:
      - default_serviceDefaultController
      description: API 欢迎信息
      operationId: DefaultController.欢迎信息
      responses:
        "200":
          description: '{string}'
  /api/group/group:
    get:
      tags:
      - group
      summary: 用户组列表
      description: 用户组列
      parameters:
      - in: query
        name: page
        description: page
        required: true
        type: string
      - in: query
        name: page_size
        description: page_size
        required: true
        type: string
      responses:
        "200":
          description: '{string}'
    post:
      tags:
      - group
      summary: 新建用户组
      description: 新建用户组
      parameters:
      - in: body
        name: body
        description: 用户组
        schema:
          $ref: '#/definitions/models.Group'
      responses:
        "200":
          description: '{string}'
  /api/group/group/{id}:
    get:
      tags:
      - group
      summary: 用户组
      description: 用户组
      parameters:
      - in: path
        name: id
        description: id
        required: true
        type: integer
      responses:
        "200":
          description: '{string}'
    put:
      tags:
      - group
      summary: 更新用户组
      description: 更新用户组 (支持部分更新)
      parameters:
      - in: path
        name: id
        description: id
        required: true
        type: integer
      - in: body
        name: body
        description: 用户组
        schema:
          $ref: '#/definitions/models.Group'
      responses:
        "200":
          description: '{string}'
    delete:
      tags:
      - group
      summary: 删除用户组
      description: 删除用户组
      parameters:
      - in: path
        name: id
        description: id
        required: true
        type: integer
      responses:
        "200":
          description: '{string}'
  /api/staffuser/info:
    get:
      tags:
      - staffuser
      summary: 获取StaffUser
      description: 获取StaffUser
      responses:
        "200":
          description: '{string}'
      security:
      - jwt: []
  /api/staffuser/staffuser:
    get:
      tags:
      - staffuser
      summary: StaffUser列表
      description: StaffUser列表
      parameters:
      - in: query
        name: page
        description: page
        required: true
        type: string
      - in: query
        name: page_size
        description: page_size
        required: true
        type: string
      responses:
        "200":
          description: '{string}'
    post:
      tags:
      - staffuser
      summary: 新建StaffUser
      description: 新建StaffUser
      parameters:
      - in: body
        name: body
        description: StaffUser
        schema:
          $ref: '#/definitions/models.StaffUser'
      responses:
        "200":
          description: '{string}'
  /api/staffuser/staffuser/{id}:
    get:
      tags:
      - staffuser
      summary: StaffUser
      description: StaffUser
      parameters:
      - in: path
        name: id
        description: id
        required: true
        type: integer
      responses:
        "200":
          description: '{string}'
    put:
      tags:
      - staffuser
      summary: 更新StaffUser
      description: 更新StaffUser (支持部分更新)
      parameters:
      - in: path
        name: id
        description: id
        required: true
        type: integer
      - in: body
        name: body
        description: StaffUser
        schema:
          $ref: '#/definitions/models.StaffUser'
      responses:
        "200":
          description: '{string}'
    delete:
      tags:
      - staffuser
      summary: 删除StaffUser
      description: 删除StaffUser
      parameters:
      - in: path
        name: id
        description: id
        required: true
        type: integer
      responses:
        "200":
          description: '{string}'
  /api_login:
    post:
      tags:
      - auth_serviceAuthController
      summary: 登录
      description: 账号登录接口
      parameters:
      - in: body
        name: body
        description: UserRegister
        schema:
          $ref: '#/definitions/extra.UserRegister'
      responses:
        "200":
          description: '{string}'
        "401":
          description: No Admin
  /auth:
    get:
      tags:
      - auth_serviceAuthController
      summary: 认证测试
      description: 测试错误码
      responses:
        "200":
          description: '{string}'
        "401":
          description: unauthorized
      security:
      - jwt: []
  /login:
    post:
      tags:
      - auth_serviceAuthController
      summary: 登录
      description: 账号登录接口
      parameters:
      - in: formData
        name: username
        description: 用户昵称
        required: true
        type: string
      - in: formData
        name: password
        description: 密码
        required: true
        type: string
      responses:
        "200":
          description: '{string}'
        "401":
          description: No Admin
  /logout:
    post:
      tags:
      - auth_serviceAuthController
      summary: 登出
      description: 账号登出接口
      responses:
        "200":
          description: '{string}'
        "401":
          description: No Admin
  /register:
    post:
      tags:
      - auth_serviceAuthController
      summary: 注册
      description: 账号注册接口
      parameters:
      - in: body
        name: body
        description: UserRegister
        schema:
          $ref: '#/definitions/extra.UserRegister'
      responses:
        "200":
          description: '{string}'
        "401":
          description: No Admin
definitions:
  extra.UserRegister:
    title: UserRegister
    type: object
    properties:
      password:
        type: string
      username:
        type: string
  models.Group:
    title: Group
    type: object
    properties:
      create_at:
        type: string
        format: datetime
      group:
        type: string
      groupname:
        type: string
      id:
        type: integer
        format: int64
      permission:
        type: string
  models.StaffUser:
    title: StaffUser
    type: object
    properties:
      create_at:
        type: string
        format: datetime
      group:
        type: string
      id:
        type: integer
        format: int64
      password:
        type: string
      username:
        type: string
securityDefinitions:
  jwt:
    type: apiKey
    description: header
    name: Authorization
    in: header
tags:
- name: github.com/zhwei820/appconfig/services/default_serviceDefaultController
  description: |
    Operations about object
- name: github.com/zhwei820/appconfig/services/default_serviceDefaultController
  description: |
    Operations about object
