// Code generated by protoc-gen-hprose , DO NOT EDIT.
// source: sing.proto

package sing

import (
	"log"
	"testing"
)



func TestCallSingHello(t *testing.T) {
	out, err := SingRpc(SingClientRpc, "SingHello", SingHelloInputBytes)
	if err != nil {
		log.Fatal("error:", err.Error())
	}
	log.Print(string(out))
}



